### ISSUE TITLE
run main.py error

### ISSUE THREAD

**Issue by LoveSimons** [charlio23/DeepSkeleton-pytorch#1]
Hello, I am very interested in your research. My research direction is edge detection. I have problems running your code:
runfile('/home/renxue/DeepSkeleton/finetune.py', wdir='/home/renxue/DeepSkeleton')
Reloaded modules: dataset
Traceback (most recent call last):

  File "/home/renxue/anaconda3/envs/pytorch/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-0a41babaedae>", line 1, in <module>
    runfile('/home/renxue/DeepSkeleton/finetune.py', wdir='/home/renxue/DeepSkeleton')

  File "/home/renxue/anaconda3/envs/pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/renxue/anaconda3/envs/pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/renxue/DeepSkeleton/finetune.py", line 2, in <module>
    from model import initialize_fsds

  File "/home/renxue/DeepSkeleton/model.py", line 102
    self.conv5 = torch.nn.Sequential(
    ^
IndentationError: unexpected indent
look forward to your reply. I wish you a happy life.

**Comment by charlio23** [comment]
Hello,

The code for finetuning is not tested yet and I cannot guarantee it works perfectly.

The readme file is outdated as I am making changes to this code every day. I advice you to run the main.py file and comment the part where I load the COCO dataset (line 46) change batch size to 1 (line 47) and uncomment line 45 to run the experiment with SK-LARGE.

It seems that the error is in the indentation of the files. Check that they are indented correctly in your computer (4 spaces).

**Comment by charlio23** [comment]
Once I have some time I will make the code cleaner and update the readme file. Sorry for that.

**Comment by LoveSimons** [comment]
Thank you very much for your reply. I will study your published code in depth and look forward to your further improvement of the code. I wish you a happy life.




------------------ 原始邮件 ------------------
发件人:  "charlio23"<notifications@github.com>;
发送时间:  2019年6月6日(星期四)晚上10:32
收件人:  "charlio23/DeepSkeleton-pytorch"<DeepSkeleton-pytorch@noreply.github.com>;
抄送:  "guanlaifu"<351161991@qq.com>;"Author"<author@noreply.github.com>;
主题:  Re: [charlio23/DeepSkeleton-pytorch] run main.py error (#1)




Once I have some time I will make the code cleaner and update the readme file. Sorry for that.
